//
//  Initialization.swift
//  NerfGunShop
//
//  Created by Joseph Lee on 14/2/22.
//

import Foundation
import UIKit

//This function runs the first time when the app is open in a new device or a reset happens
//Usually run in ViewController.swift
func initializeData() {
    
    //Insert Categories
    insertCategory(name: "Nerf Blasters", description: "A Nerf Blaster is a toy gun made by Hasbro that fires foam darts, discs, or foam balls. The term 'Nerf gun' is often used to describe the toy; however, it is often used as a blanket term for any foam dart blaster, regardless of whether or not it has the Nerf brand name. Nerf blasters are manufactured in multiple forms; the first Nerf blasters emerged in the late 1980s with the release of the Nerf Blast-a-Ball and Arrowstorm. Today, Hasbro has produced over twenty unique lines of Nerf-brand blasters, which each line centered around a particular theme or type of ammunition. Moreover, Hasbro has also produced Nerf blasters based around specific franchises, including Marvel Comics, Star Wars, G.I. Joe, Fortnite, Transformers, Overwatch, Halo Infinite, and Roblox. Nerf blasters are available in several international markets, although some blasters have their names changed or are not sold in certain countries due to laws surrounding toy safety.", imageName: "nerf_logo")
    insertCategory(name: "X-Shot Blasters", description: "Our mission at x-shot is to deliver unbeatable value to our fans worldwide. This is a combination of design excellence and market-leading quality with unbeatable prices. Become an x-shooter and don’t waste your hard-earned money to get battle ready. We are taking it to the next level. Join us.", imageName: "xshot_logo")
    insertCategory(name: "Darts", description: "Refill darts for blaster guns", imageName: "dart")
    
    //Insert products
    insertProduct(name: "Nerf Ultra Dorado", description: "Go for the ultimate gold -- in dart blasting! Decorated with premium gold accents, the Nerf Ultra Dorado blaster includes 12 special edition gold-colored Nerf Ultra darts. This motorized, 6-dart blaster fires darts fast. Power up the motor and press the trigger to fire 1 dart at a time. Fast back loading lets you reload quickly -- the 6-dart cylinder has an open back, so you can see how many darts are left and know when to reload. Includes on-board 6-dart storage. Nerf Ultra blasters take your game to the next level with their advanced design and performance that delivers extreme distance, accuracy, and speed. Nerf Ultra darts are the farthest flying Nerf darts EVER and have an innovative flight tip, Aerofin technology, and Nerf Ultra foam. Fires darts up to 120 feet (36 meters). Nerf Ultra blasters work only with Nerf Ultra darts. Batteries required (not included). Eyewear recommended (not included).", price: 52, categoryId: 1, imageName: "Nerf Ultra Dorado")
    insertProduct(name: "NERF Halo MA40", description: "The Nerf Halo MA40 blaster is inspired by the one in Halo Infinite, capturing the look of the blaster from the next chapter in this legendary video game franchise! Imagine yourself as the Master Chief and go into battle against the alien alliance! Challenge opponents with this motorized, clip-fed blaster that unleashes 10 darts in a row. It comes with a removable, 10-dart clip and 10 Official Nerf darts, enough to fully load the clip. The Nerf Halo MA40 blaster includes a game card with a code to unlock a digital asset in the Halo game.* To start playing, hold down the acceleration button to power up the blaster's motor, then press the trigger to fire 1 dart. Press the trigger again to fire another dart. It comes with a rail riser that attaches to the blaster's tactical rail, so you can customize the blaster with Nerf accessories (not included). Eyewear recommended (not included).", price: 100, categoryId: 1, imageName: "NERF Halo MA40")
    insertProduct(name: "Nerf Ultra One Motorised Blaster", description: "Experience Nerf Ultra blaster -- the gold standard in Nerf dart blasting! Nerf Ultra blasters have advanced design and performance to deliver extreme distance, accuracy, and speed. They include ground-breaking Nerf Ultra darts -- the farthest flying Nerf darts EVER, featuring an innovative flight tip, Aerofin technology, and Nerf Ultra foam. Take your game to the next level with Nerf Ultra blasters and darts! Nerf Ultra blasters work only with Nerf Ultra darts.\n\nThe Nerf Ultra One motorized blaster has a high-capacity 25-dart dart drum and comes with 25 Nerf Ultra darts. Fire over 2 dozen darts with the high-performance advantages of this Nerf Ultra blaster. Send darts flying through the air up to 120 feet (36 meters). There's on-board dart storage for quick reloading. You have the skills and the expertise as a Nerf battler, now you have the blaster and darts for game-changing superiority!", price: 100, categoryId: 1, imageName: "Nerf Ultra One Motorized Blaster")
    insertProduct(name:"NERF Roblox MM2: Shark Seeker", description: "This Nerf Roblox MM2: Shark Seeker blaster takes its inspiration from the Roblox game MM2. It includes a special code that allows you to redeem an exclusive virtual item on Roblox!* The blaster features an awesome shark design including a fin that you move to prime the blaster. It comes with 3 Nerf Mega foam darts. To start blasting, load 3 darts into the front of the blaster, move the top fin backward and forward, and press the trigger to fire 1 dart. Official Nerf Mega foam darts are tested and approved for performance and quality, and are great for indoor and outdoor play. Eyewear recommended (not included). No batteries required.", price: 50, categoryId: 1, imageName: "NERF Roblox MM2: Shark Seeker")
    insertProduct(name: "NERF Roblox Jailbreak: Armory Blaster 2 Pack", description: "These 2 dart blasters in this Roblox Jailbreak: Armory set take their inspiration from the Roblox Jailbreak game! This blaster pack includes a special code that allows you to redeem an exclusive virtual item on Roblox!* The blasters feature hammer-action priming and are easy to use to get you playing fast. Load 1 dart into the barrel, pull down the priming hammer, and press the trigger to fire the dart. The set comes with 10 Official Nerf Elite foam darts, so you have plenty on hand for multiple reloads. Share one blaster with someone to re-create the action in Jailbreak as you launch into a competitive game to test your dart-blasting skills! Eyewear recommended (not included). No batteries required.", price: 42, categoryId: 1, imageName: "NERF Roblox Jailbreak: Armory Blaster 2 Pack")
    insertProduct(name: "NERF Elite 2.0 Shockwave RD-15", description: "Gear up for battle with Nerf Elite 2.0 blasters that feature built-in customizing capabilities so you can upgrade them and seize the advantage in Nerf competitions. Build your stockpile of Nerf Elite 2.0 blasters to optimize your game strategy and bring tactical performance and flexibility to every mission and battle!\n\nThe Nerf Elite 2.0 Shockwave RD-15 blaster features customizing capabilities that include 3 tactical rails, barrel attachment point, and stock attachment point to optimize for battle. This pump-action blaster has a 15-dart rotating drum to swamp your targets. Pull the priming slide back and press the trigger to unleash 1 dart, or hold down the trigger and keep moving the slide to slam-fire all 15 darts. Includes 30 Official Nerf darts -- 15 for the drum, and 15 for reloads. Fires darts up to 90 ft (27 m). Eyewear recommended. Barrel extension, stock, and eyewear not included. No batteries required.", price: 50, categoryId: 1, imageName: "NERF Elite 2.0 Shockwave RD-15")
    insertProduct(name: "NERF Fortnite SMG-Zesty", description: "The Nerf Fortnite SMG-Zesty blaster is inspired by the Zesty Wrap in Fortnite, capturing the look of the Wrap from the popular video game! The blaster features a detachable barrel and a detachable stock so you can customize it different ways. Attach them, detach them -- it's all up to you! Remove them when you're battling in close quarters for a more compact blaster style. Try adding the barrel for distance targeting! The blaster comes with a 10-dart clip and 10 Nerf Elite darts. To get blasting, load the clip into the blaster, move the slide to prime, and press the trigger to fire 1 dart. Official Nerf Elite foam darts great for indoor and outdoor battles, and are tested and approved for performance and quality. No batteries needed. Eyewear recommended (not included).", price: 65, categoryId: 1, imageName: "NERF Fortnite SMG-Zesty")
    insertProduct(name: "NERF Fortnite B-AR", description: "The Nerf Fortnite B-AR blaster is inspired by the equipment used in Fortnite and comes in the Converge Wrap from the popular video game! The blaster powers you up for action with motorized dart blasting. Choose your targets and fire off 10 darts in a row from this Nerf Fortnite blaster that includes a removable 10-dart clip and 10 Official Nerf Elite darts. Load the clip into the blaster, then hold down the acceleration button and pull the trigger to fire a dart. Nerf darts are made of foam, so they're great for both indoor and outdoor battles. Eyewear recommended (not included). Requires 4x 1.5v C alkaline batteries (not included).", price: 85, categoryId: 1, imageName: "NERF Fortnite B-AR")
    insertProduct(name: "NERF Fortnite Heavy SR", description: "nspired by the equipment used in Fortnite, the Nerf Heavy SR blaster captures the look of the equipment in the popular video game. This is the longest Nerf Fortnite blaster ever, measuring an awesome 43 inches long (1.1 meter) from barrel to stock! Step onto the field -- just the size of this blaster alone is enough to impress -- and intimidate -- your opponents. Now go ahead and take those long-distance shots to take control of the game! The blaster features the Red Camo Wrap from the game. It includes a 6-dart clip and 6 Official Nerf Mega foam darts that unleash with bolt-action priming. Load the clip into the blaster, slide the bolt to ready a dart for firing, then press the trigger to blast the dart toward your target. No batteries required. Eyewear recommended (not included).", price: 100, categoryId: 1, imageName: "NERF Fortnite Heavy SR")
    insertProduct(name: "NERF Fortnite GL Blaster", description: "Play Fortnite in real life with the dart-firing Nerf Fortnite SR blaster that is inspired by the one used in Fortnite, capturing the look of the one from the popular video game. The SR blaster features 4-dart hammer action so you can fire 4 darts in a row before reloading. Take aim at your target and press the trigger to unleash 1 dart. To launch another dart, pull back the hammer, and press the trigger. Use the removable scope to help you line up your shot. The Nerf Fortnite SR blaster comes with 8 Nerf Elite darts, enough to fully load the blaster, with 4 darts for backup firepower when it's time to reload. Official Nerf darts are made of foam and are tested and approved for performance and quality. No batteries required. Eyewear recommended (not included).", price: 130, categoryId: 1, imageName: "NERF Fortnite GL Blaster")
    insertProduct(name: "NERF Elite 2.0 Flipshots Flip-32 Blaster", description: "Flip into battle with the Nerf Elite 2.0 Flipshots Flip-32 blaster! The blaster features 32 barrels -- 16 face forward and 16 face backward. Fire darts from the 16 front-facing barrels, then flip the 16 rear barrels forward to keep on blasting darts. Just when your opponents think you’re out, you can take them by surprise with 16 more fully-loaded barrels! The back-to-back barrels are connected, making it quick and easy to rotate them by pulling the handle. Fire 1 or 2 darts at a time – pull the trigger halfway to fire 1 dart, or pull it all the way back to fire 2 darts. The blaster has lever-action priming. Each barrel holds 1 dart, giving the blaster a 32-dart capacity. Includes 32 Official Nerf Elite 2.0 foam darts. Eyewear recommended (not included). Hand-powered by you (no batteries required). ", price: 130, categoryId: 1, imageName: "NERF Elite 2.0 Flipshots Flip-32 Blaster")
    insertProduct(name: "NERF N-Strike Elite Mega Cycloneshock Blaster", description: "Your battles are about to get a whole lot bigger – Mega bigger! The CycloneShock blaster has the same high performance as other N-Strike Elite blasters, but it features bigger darts engineered to fire farther than ever! The rotating drum lets you fire 6 Mega Darts without reloading! Hit the battlefield – and targets up to 90 feet away - with the rapid-firing Mega power of the CycloneShock blaster!", price: 42, categoryId: 1, imageName: "NERF N-Strike Elite Mega Cycloneshock Blaster")
    insertProduct(name: "Nerf Ultra Two", description: "Experience the ultimate in Nerf dart blastings! Nerf Ultra blasters have advanced design and performance to deliver extreme distance, accuracy, and speed. They include ground-breaking Nerf Ultra darts -- the farthest flying Nerf darts EVER, featuring an innovative flight tip, Aerofin technology, and Nerf Ultra foam. Take your game to the next level with Nerf Ultra blasters and darts! Nerf Ultra blasters work only with Nerf Ultra darts. ", price: 50, categoryId: 1, imageName: "Nerf Ultra Two")
    insertProduct(name: "NERF N-Strike Icon Series Spectre Rev-5", description: "The Icon Series brings back your favorite Nerf blasters updated for today! This version of the classic Nerf N-Strike Spectre Rev-5 blaster is decked out with a special Icon Series colors, and comes with 10 Official Nerf Elite darts, also with special Icon Series deco. Create 6 different blaster configurations with the included barrel extension and folding stock -- both are removable so you can customize for any mission or battle. For distance targeting, try adding the barrel extension. Take advantage of the folding stock to help steady your shots. The rotating barrel holds 5 darts and swings open when you press a button for easy loading. To fire, pull the priming slide back, line up your shot, and press the trigger to fire 1 dart. Includes 10 Official Nerf Elite darts, enough to fully load the drum with 5 more for backup firepower. No batteries required. Eyewear recommended (not included).", price: 60, categoryId: 1, imageName: "NERF N-Strike Icon Series Spectre Rev-5")
    insertProduct(name: "NERF Ultra Three Blaster", description: "Experience Nerf Ultra blasters -- the ultimate in Nerf dart blasting! Nerf Ultra blasters have advanced design and performance to deliver extreme distance, accuracy, and speed. They include ground-breaking Nerf Ultra darts -- the farthest flying Nerf darts EVER, featuring an innovative flight tip, Aerofin technology, and Nerf Ultra foam. Take your game to the next level with Nerf Ultra blasters and darts! Nerf Ultra blasters work only with Nerf Ultra darts.\n\nThe Nerf Ultra Three blaster features pump-action blasting and an 8-dart internal clip. Show your dart-firing skills as you pump the priming handle and press the trigger to fire 8 darts in a row before it's time to reload. On-board storage for 4 darts (additional darts sold separately). Includes 8 Nerf Ultra darts that are compatible only with Nerf Ultra blasters. Send darts flying through the air up an awesome to 120 feet (36 meters)! Eyewear recommended (not included).", price: 65, categoryId: 1, imageName: "NERF Ultra Three Blaster")
    insertProduct(name: "NERF Elite 2.0 Warden DB-8", description: "Gear up for battle with Nerf Elite 2.0 blasters that feature built-in customizing capabilities so you can upgrade them and seize the advantage in Nerf competitions. Build your stockpile of Nerf Elite 2.0 blasters to optimize your game strategy and bring tactical performance and flexibility to every mission and battle!\n\nThe Nerf Elite 2.0 Warden DB-8 blaster fires 2 darts at once to send a double dose of firepower at your targets. It has an 8-dart capacity, so you can launch a series of darts at the competition before reloading. Take advantage of the tactical rail to customize the blaster for every mission or battle. Fire all 8 darts rapidly with pump-action slam-fire! Includes 16 Official Nerf darts -- 8 darts to load into the blaster, and 8 darts for reloading. Fires darts up to 85 feet (26 meters). Eyewear recommended (not included) No batteries required.", price: 42, categoryId: 1, imageName: "NERF Elite 2.0 Warden DB-8")
    insertProduct(name: "X-Shot Vigilante", description: "The vigilante is a twin-barrel, pump-action blaster that takes you back to the wild-west! Break N' Load To target your opponents with this extremely powerful weapon!", price: 28, categoryId: 2, imageName: "X-Shot Vigilante")
    insertProduct(name: "X-Shot Micro Dart Blaster", description: "Don’t be fooled by its size, the X-Shot MICRO blaster is shockingly powerful! Small but accurate, the Micro blaster can fire from up to 80 feet / 24 meters and allows for quick responses that will definitely catch your opponents by surprise! With dart storage on top, the Micro is easy to reload and can serve as the perfect concealed weapon!", price: 6, categoryId: 2, imageName: "X-Shot Micro Dart Blaster")
    insertProduct(name: "NERF Elite 2.0 80-Dart Refill Pack", description: "Stock up with this Nerf Elite 2.0 refill pack of 80 Official Nerf Elite 2.0 darts and have plenty of firepower on hand to reload your Nerf Elite 2.0 blasters! It happens all the time -- some darts go missing when you're blasting away in a Nerf battle. Instead of stopping the game and searching for darts, keep refills nearby so you spend less time looking for darts and more time playing! With this 80-dart refill set, you can reload Nerf Elite 2.0 blasters and keep on battling. Reload with Official Nerf foam darts -- they're tested and approved for performance and quality. Nerf Elite 2.0 darts are compatible with all Official Nerf blasters that use Elite darts. Gear up for battle with Nerf Elite 2.0 blasters that feature built-in customizing capabilities so you can upgrade them and seize the advantage in Nerf competitions! Blasters each sold separately. Eyewear recommended (not included).", price: 23, categoryId: 3, imageName: "NERF Elite 2.0 80-Dart Refill Pack")
    insertProduct(name: "NERF Darts N-Strike Mega Series 10-Pack Refill Darts", description: "Get 10 Mega Darts for mega distance! This 10-pack of far-flying darts gives you the ammo you need to get an edge on the battlefield. They work with most N-Strike blasters (sold separately). Ammo up with this Mega Series 10-pack!", price: 13, categoryId: 3, imageName: "NERF Darts N-Strike Mega Series 10-Pack Refill Darts")
    insertProduct(name: "NERF 30 Dart Elite Refill Pack", description: "Blast with Official Nerf Darts -- the darts that hit the mark for performance and quality! Stock up on this refill pack of 30 Nerf Elite darts and be ready to reload when Nerf competitions heat up. Nerf Elite darts are designed for distance and blast up to 85 feet (26 meters).* They are compatible with all Nerf toy blasters that use Elite darts, so players can use also them with N-Strike Elite, AccuStrike Elite, Zombie Strike, and Modulus blasters. Nerf darts are constructed of foam with flexible, hollow tips, making them fun to blast -- and get blasted with -- indoors and outdoors. Load Nerf blasters with tested and approved Official Nerf Darts, the darts that deliver performance and quality with every blast! Blasters each sold separately.", price: 16, categoryId: 3, imageName: "NERF 30 Dart Elite Refill Pack")
    insertProduct(name: "X-Shot 100 Darts Refill Pack - Assorted", description: "Never lose out on the action with this handy 100 dart refill in window Box!  X-Shot darts are compatible with most leading brands and offer the best value with its amazing light foam technology! ", price: 25, categoryId: 3, imageName: "X-Shot 100 Darts Refill Pack - Assorted")
    insertProduct(name: "NERF Darts Ultra 20 Darts Refill", description: "Nerf Darts for the Nerd Ultra series guns", price: 17, categoryId: 3, imageName: "NERF Darts Ultra 20 Darts Refill")
    insertProduct(name: "Zuru X-Shot Dino Attack Ultimate Dino Attack Combo", description: "The new X-Shot Dino Attack range is here! Get ready for the Dino invasion with the Ultimate Dino Attack Combo Pack featuring the Dino Striker blaster with its auto-rotating barrel & the shot-gun style Claw Hunter blaster. This combo pack includes multiple Dino egg targets and a massive amount of foam darts. Join the eggs together, place them down and then blast them away before they hatch! Annihilate Dino Eggs with extreme accuracy from up to 90ft / 27m away. With this blaster combination no invader stands a chance.", price: 56, categoryId: 2, imageName: "Zuru X-Shot Dino Attack Ultimate Dino Attack Combo")
    insertProduct(name: "X-Shot Excel Hurricane Clip Blaster Dart (16 Darts)", description: "The X-Shot Hurricane is a clip blaster that allows you to shoot 10 darts up to 80ft/24m in a quick succession without reloading! When you’re out of ammo getting back into action is simple: release the dart clip, fill with darts, reload and blast! ", price: 21, categoryId: 2, imageName: "X-Shot Excel Hurricane Clip Blaster Dart (16 Darts)")
    insertProduct(name: "X-Shot-Excel Reflex 6 (16 Darts)", description: "Annihilate your opponents and blast without hesitation with the X-Shot Reflex 6 dart blaster from Zuru. It has a high-perfromance auto-rotating barrel that can hold 6 darts and blast the entire load within 15 seconds. Speed and frequency make this blaster unstoppable! Prime, lock 'n' load before firing your foam darts over 27 meters / 90 feet. Up your game and leave your opponents not chance." , price: 13, categoryId: 2, imageName: "X-Shot-Excel Reflex 6 (16 Darts)")
    insertProduct(name: "X-Shot Excel Vigilante (24 Darts)", description: "VIGILANTE: The X-Shot Vigilante's pump action handle and quick fire mechanism sees the blaster capable of shooting up to 27 metres / 90 feet ; CRACK AND LOAD FUNCTION: Break N' load to target your opponents with this extremely powerful weapon! Also comes with back-loading mag.", price: 28, categoryId: 2, imageName: "X-Shot Excel Vigilante (24 Darts)")
    insertProduct(name: "X-Shot Excel Turbo Advance", description: "The X-Shot Turbo Advance is the 40-Darts Barrel Capacity monstrosity that your arsenal was missing! Thanks to its easy-to-prime mechanism you can make it rain darts over your opponents! In the most unlikely case you run out of darts, simply detach your barrel from the Turbo Advance to easily refill it and go back to action! Tap on the switch on its side to flick through the two layers of darts in the barrel, and hit your opponents from over 66 feet / 20 meters! We are pretty confident we've got you covered with this one!", price: 56, categoryId: 2, imageName: "X-Shot Excel Turbo Advance")
    insertProduct(name: "Zuru X-Shot Dino Attack Extinct", description: "The new X-Shot Dino Attack range is here! Get ready for the Dino invasion with the new Extinct blaster providing extreme accuracy from 90ft / 27m away. With its single dart barrel and additional 4 dart storage, you will be locked and loaded for battle. Use your Dino Egg for target practice and flip out the exclusive retractable sword to tackle even the fiercest of Dinos.", price: 12, categoryId: 2, imageName: "Zuru X-Shot Dino Attack Extinct")
    insertProduct(name: "X-Shot Mk 3 Double Pack", description: "The X-Shot MK 3 allows you to blast 3 darts in quick succession thanks to its rotating barrel! Hit targets from up to 27 meters / 90 feet with total accuracy! The ultimate blaster for attacks requiring speed and agility!", price: 15, categoryId: 2, imageName: "X-Shot Mk 3 Double Pack")
    
}
